server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: api
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          app: api
          env: dev
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            method: method
            path: path
            status_code: status_code
            process_time: process_time
            client_ip: client_ip
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          method:
          path:
          status_code:
          client_ip: 