server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'job'

  - job_name: api
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          app: api
          env: development
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            method: method
            path: path
            status_code: status_code
            process_time: process_time
            client_ip: client_ip
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          method:
          path:
          status_code:
          client_ip:
      - output:
          source: message

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          app: system
          env: development
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>[\d\-]+T[\d:\.]+Z) (?P<level>\w+) (?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
      - output:
          source: message

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          app: docker
          env: development
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            container: container
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          container:
      - output:
          source: message 